---
- name: Setup Kubernetes master node
  hosts: master
  become: true
  
  tasks:
    # Initialize Kubernetes cluster
    - name: Initialize Kubernetes cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=10.0.1.10 --ignore-preflight-errors=Swap
      register: kubeadm_output
      args:
        creates: /etc/kubernetes/admin.conf
    
    # Setup kubectl for ec2-user
    - name: Create .kube directory
      file:
        path: /home/ec2-user/.kube
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'
    
    - name: Copy admin.conf to user kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ec2-user/.kube/config
        remote_src: yes
        owner: ec2-user
        group: ec2-user
        mode: '0644'
    
    # Install Calico network plugin
    - name: Install Calico network
      shell: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/calico.yaml
      become_user: ec2-user
      environment:
        KUBECONFIG: /home/ec2-user/.kube/config
    
    # Generate join command for workers
    - name: Generate join command
      shell: kubeadm token create --print-join-command
      register: join_command
    
    - name: Save join command to file
      copy:
        content: "{{ join_command.stdout }}"
        dest: /tmp/join-command.sh
        mode: '0755'
    
    - name: Display join command
      debug:
        msg: "Join command: {{ join_command.stdout }}"
